version: '3.8'

services:
  admin-panel:
    build:
      context: ./admin/admin
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5433/postgres
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL:-https://default.supabase.co}
      - NEXT_PUBLIC_SUPABASE_KEY=${NEXT_PUBLIC_SUPABASE_KEY:-default-key}
    depends_on:
      - db
    volumes:
      - ./admin/admin:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  bot-service:
    build:
      context: ./instagram_bot
    environment:
      - INSTAGRAM_USER=${INSTAGRAM_USER:-testuser}
      - INSTAGRAM_PASSWORD=${INSTAGRAM_PASSWORD:-testpass}
    depends_on:
      - db
    volumes:
      - ./instagram_bot:/app
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import instagram_bot; instagram_bot.main.check_health()\""]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: