services:
  # PHP Service (Application Backend)
  app:
    build:
      context: .                      # Path to the project root directory
      dockerfile: ./docker/php/Dockerfile  # Relative path to your PHP Dockerfile
    container_name: arinaadmin_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      DB_CONNECTION: ${DB_CONNECTION:-pgsql}
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_DATABASE: ${DB_DATABASE:-zirofit_db}
      DB_USERNAME: ${DB_USERNAME:-user}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      APP_NAME: ${APP_NAME:-Laravel}
      APP_ENV: ${APP_ENV:-local}
      APP_KEY: ${APP_KEY}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8080}
      LOG_CHANNEL: ${LOG_CHANNEL:-stderr}
      CACHE_STORE: ${CACHE_STORE:-database}
      SESSION_DRIVER: ${SESSION_DRIVER:-database}
      QUEUE_CONNECTION: ${QUEUE_CONNECTION:-database}
      VITE_APP_NAME: "${APP_NAME}"
      VITE_SERVER_HOST: 0.0.0.0
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:delegated
    ports:
      - "5173:5173"
    networks:
      - arinaadmin_network
    depends_on:
      - db

  # Webserver Service (Apache)
  webserver:
    image: httpd:2.4 # Use official Apache image
    container_name: arinaadmin_webserver
    restart: unless-stopped
    tty: true
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - ./:/var/www/html
      - ./docker/apache/default.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    # Command to:
    # 1. Ensure our vhost config is included (if not already)
    # 2. Start Apache in the foreground (sed commands removed)
    command: >
      /bin/sh -c "
      if ! grep -q 'Include /usr/local/apache2/conf/extra/httpd-vhosts.conf' /usr/local/apache2/conf/httpd.conf; then echo 'Include /usr/local/apache2/conf/extra/httpd-vhosts.conf' >> /usr/local/apache2/conf/httpd.conf; fi && \
      httpd-foreground
      "
    networks:
      - arinaadmin_network
    depends_on:
      - app
  # PostgreSQL Database Service
  db:
    image: postgres:17
    container_name: arinaadmin_db
    restart: unless-stopped
    tty: true
    ports:
      - "${DB_HOST_PORT:-54321}:5432"
    environment:
      # Set PostgreSQL credentials using variables from host .env file or defaults
      POSTGRES_DB: ${DB_DATABASE:-zirofit_db}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    networks:
      - arinaadmin_network

# Define the custom network
networks:
  arinaadmin_network:
    driver: bridge

# Define named volumes
volumes:
  db_data:
    driver: local
