version: "3.8"

services:
  admin-panel:
    build:
      context: ./admin/admin
    ports:
      - "3000:3000"
    env_file:
      - ./admin/admin/.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./admin/admin:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 5

  bot-service:
    build:
      context: ./instagram_bot
    env_file:
      - ./instagram_bot/.env
    environment:
      - RUN_MODE=continuous
    depends_on:
      - db
    volumes:
      - ./instagram_bot:/app
    healthcheck:
      test: ["CMD-SHELL", "python main.py check_health"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
